### PR TITLE
Added the double entry principle

### PR DESCRIPTION
**Pull request by olamilekan000**
the double entry principle was added.

### CODE REVIEW

**Comment by koresar** [comment]
Oh, nice. Thank you very much, Olya.

**Comment by olamilekan000** [comment]
Do you not intend on createing an interface for the app?

**Comment by koresar** [comment]
@olamilekan000 I struggle to understand your message. Would please rephrase your question?

**Comment by olamilekan000** [comment]
I mean a UI for your application. Are you not making one?

**Comment by koresar** [comment]
This module is a low-level library which should be used by any node.js application. Creating a UI for such a module is a very unexpected move.

No, we do not plan to do that. Sorry.

**Comment by olamilekan000** [comment]
Ok. I was thinking since it's an accounting system a UI should go with it but it's all good.

**Pull request merged**
